[package]
name = "apartment-app"
version = "0.1.0"
authors = ["Danny <pinghedm@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["handlebars_templates"]
